# CNN Count Diffusion Model Configuration
_target_: architecture.cnn_multimodal.CNNCountDiffusion

# Image parameters
img_size: 256
in_channels: 1

# Count parameters  
count_dim: ${dataset.data_dim}

# Noise parameters
noise_dim: ${model.noise_dim}

# Architecture parameters - more efficient
base_channels: 48
channel_multipliers: [1, 2, 4, 8]
num_res_blocks: 2
time_embed_dim: 512

# Training parameters
dropout: 0.1
