# MLP Architecture Configuration for Counting Flows with Energy Score
_target_: architecture.mlp.MLP

# Input dimensions: [x_t, t, M_t, noise]
in_dims: 
  - ${dataset.data_dim}
  - 1
  - ${dataset.data_dim}
  - ${model.noise_dim}
hidden_dim: 64
out_dim: ${dataset.data_dim}
layers: 3 