# MLP Architecture Configuration for Counting Flows with MSE (deterministic, no noise)
_target_: architecture.mlp.MLP

# Input dimensions: [x_t, t, M_t] (no noise for deterministic MSE)
in_dims: 
  - ${dataset.data_dim}
  - 1
  - ${dataset.data_dim}
hidden_dim: 64
out_dim: ${dataset.data_dim}
layers: 3 