# ARDigit Model Configuration
_target_: models.ardigit.ARDigitTransformer

# Model architecture
x_dim: ${data_dim}
context_dim: 0  # No conditioning for simplified approach
hidden: 128
d_model: 128
nhead: 4
num_layers: 2

L: 3
base: 10
