# Energy Score Loss Configuration
_target_: models.energy_deconv.DeconvolutionEnergyScoreLoss

# Architecture (use MLP by default)
architecture: ${architecture}

# Energy score parameters
noise_dim: 128
m_samples: 4
lambda_energy: 1.0