# Energy Score Loss Configuration
_target_: models.energy.EnergyScoreLoss

# Architecture (use MLP by default)
architecture: ${architecture}

# Energy score parameters
noise_dim: 100
m_samples: 32
lambda_energy: 1.0