# Multimodal Deconvolution Energy Score Loss Configuration
_target_: models.energy_multimodal_deconv.MultimodalDeconvolutionEnergyScoreLoss

# Architecture (will be injected from architecture config)
architecture: ${architecture}

# Energy score parameters
noise_dim: 128
m_samples: 4  # Smaller for faster testing
lambda_energy: 1.0