# Poisson Mixture Dataset Configuration
_target_: datasets.gaussian_deconv.DeconvolutionGaussianMixtureDataset

# Dataset parameters
size: 5000 
base_size: 50000  # total samples in dataset (pre-sampled for speed)
group_size: 10  # number of samples in each group
data_dim: 1
value_range: 256
min_value: 0

# Mixture parameters
k: 5  # number of mixture components
mean_scale: 20.0  # scale for sampling mixture component means in latent space
cov_scale: 10.0  # scale for sampling covariance eigenvalues in latent space
min_eigenvalue: 0.1  # minimum eigenvalue to ensure positive definiteness

# Random seed for reproducibility
seed: 42
context_dim: 5