# Gaussian Mixture Dataset Configuration
_target_: datasets.gaussian_mixture.GaussianMixtureDataset

# Dataset parameters
size: 50000  # total samples in dataset (pre-sampled for speed)
data_dim: 8
value_range: 128
min_value: 0

# Mixture parameters
k: 5  # number of mixture components
mean_scale: 10.0  # scale for sampling mixture component means
cov_scale: 5.0  # scale for sampling covariance eigenvalues
min_eigenvalue: 0.1  # minimum eigenvalue to ensure positive definiteness

# Random seed for reproducibility
seed: 42
