# Gaussian Mixture Dataset Configuration - 2D
_target_: datasets.gaussian_mixture.GaussianMixtureDataset

# Dataset parameters
size: 50000  # total samples in dataset (pre-sampled for speed)
data_dim: 2
value_range: 256
min_value: 0

# Mixture parameters
k: 5  # number of mixture components
mean_scale: 20.0  # scale for sampling mixture component means in latent space
cov_scale: 10.0  # scale for sampling covariance eigenvalues in latent space
min_eigenvalue: 0.1  # minimum eigenvalue to ensure positive definiteness

# Random seed for reproducibility
seed: 42
