# Poisson Mixture Dataset Configuration
_target_: datasets.poisson_mixture.PoissonMixtureDataset

# Dataset parameters
size: 50000  # total samples in dataset (pre-sampled for speed)
data_dim: 4
max_value: 128

# Mixture parameters
k: 3  # number of mixture components
lambda_scale: 10.0  # scale for sampling lambda parameters