# Poisson Mixture Dataset Configuration
_target_: datasets.poisson_mixture.PoissonMixtureDataset

# Dataset parameters
size: 50000  # total samples in dataset (pre-sampled for speed)
data_dim: 8
value_range: 128
min_value: 0

# Mixture parameters
k: 5  # number of mixture components
lambda_scale: 16.0  # scale for sampling lambda parameters