# Default Training Configuration

# Trainer instantiation
_target_: training.CountFlowTrainer

# Training parameters
num_epochs: 500
learning_rate: 2e-4
weight_decay: 0.0

# Device and computation
device: ${device}

# DataLoader parameters
batch_size: 256
shuffle: true
num_workers: 0

# Logging and checkpointing
print_every: 10
save_every: 25
checkpoint_dir: ${logging.checkpoint_dir}