# Default Training Configuration

# Trainer instantiation
_target_: training.Trainer

# Training parameters
num_epochs: 500

# Device and computation
device: ${device}

# DataLoader parameters
batch_size: 256
shuffle: true
num_workers: 0

# Logging and checkpointing
print_every: 10
save_every: 50
# output_dir is now passed automatically by main.py
clip_grad_norm: 1.0