# Default Training Configuration

# Trainer instantiation
_target_: training.FlowTrainer

# Training parameters
num_epochs: 500
learning_rate: 2e-4
weight_decay: 0.0

# Device and computation
device: ${device}

# DataLoader parameters
batch_size: 1
shuffle: true
num_workers: 0

# Logging and checkpointing
print_every: 1
save_every: 5
# output_dir is now passed automatically by main.py

classifier_free_guidance_prob: 0.1