# Default Training Configuration

# Trainer instantiation
_target_: training.Trainer

# Training parameters
num_epochs: 500

# Device and computation
device: ${device}

# DataLoader parameters
batch_size: 1
shuffle: true
num_workers: 12

# Logging and checkpointing
print_every: 1
save_every: 1
# output_dir is now passed automatically by main.py

classifier_free_guidance_prob: 0.1
target_sum_projection_prob: 0.1