# Default Training Configuration

# Trainer instantiation
_target_: training_deconv.DeconvTrainer

# Training parameters
num_epochs: 5000


# Device and computation
device: ${device}

# DataLoader parameters
batch_size: 256
shuffle: true
num_workers: 4

# Logging and checkpointing
print_every: 10
save_every: 50
# output_dir is now passed automatically by main.py
