defaults:
  - bridge: skellam
  - model: coral
  - architecture: mlp
  - architecture/in_dims: standard
  - architecture/out_dim: discrete
  - dataset: poisson_mixture
  - training: default
  - slack_sampler: bessel
  - _self_

# override min_value and max_value in model/cross_entropy.yaml
bridge:
  delta: false 

# Hydra configuration
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Global settings
device: cuda
seed: 42
n_steps: 30
train_split: 0.8

# Experiment settings
experiment:
  name: "counting_flows_experiment"
  version: "1.0"
  description: "Count-based flow matching with GPU bridges"

# Logging
logging:
  level: INFO

# Plotting (handled automatically by main.py)
create_plots: true 