defaults:
  - bridge: skellam
  - model: energy_score
  - dataset: poisson_mixture
  - training: default
  - _self_

# Hydra configuration
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Global settings
device: cuda
seed: 42
data_dim: 4
n_steps: 30

# Experiment settings
experiment:
  name: "counting_flows_experiment"
  version: "1.0"
  description: "Count-based flow matching with GPU bridges"

# Logging and saving
logging:
  level: INFO
  save_checkpoints: true
  checkpoint_dir: checkpoints
  log_interval: 1000

# Visualization settings
visualization:
  enabled: true
  plot_interval: 5000
  save_plots: true
  plot_dir: plots 