defaults:
  - bridge: skellam
  - model: energy_score
  - architecture: mlp
  - architecture/in_dims: with_noise
  - architecture/out_dim: scalar
  - dataset: low_rank_gaussian_mixture_5d
  - training: default
  - slack_sampler: bessel
  - _self_

# Hydra configuration
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Global settings
device: cuda
seed: 42
train_split: 0.8  # 80% train, 20% eval

# Experiment settings
experiment:
  name: "counting_flows_experiment"
  version: "1.0"
  description: "Count-based flow matching with GPU bridges"

# Logging
logging:
  level: INFO

# Plotting (handled automatically by main.py)
create_plots: true 