defaults:
  - bridge: dfm
  - model: cross_entropy
  - architecture: mlp
  - architecture/in_dims: standard
  - architecture/out_dim: discrete
  - dataset: low_rank_gaussian_mixture_5d
  - training: default
  - _self_

# Hydra configuration
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Global settings
device: cuda
seed: 42
train_split: 0.8  # 80% train, 20% eval

# Experiment settings
experiment:
  name: "dfm"
  version: "1.0"
  description: "DFM"

# Logging
logging:
  level: INFO

# Plotting (handled automatically by main.py)
create_plots: true 