# @package _global_
defaults:
  - override /training: default
  - override /dataset: poisson_mixture
  - override /bridge: skellam
  - override /model: energy_score

# Quick experiment settings
experiment:
  name: "quick_test"
  description: "Quick test run for development"

# Reduced settings for fast iteration
training:
  num_epochs: 20
  print_every: 2
  save_every: 10
  learning_rate: 3e-3  # Slightly higher for quick convergence
  batch_size: 32

dataset:
  size: 1000
  d: 5
  k: 2  # Simpler mixture for quick test
  lambda_scale: 8.0
  resample_every: 200

# Global overrides
data_dim: 5
n_steps: 25

# Logging
logging:
  level: INFO
  save_checkpoints: true
  checkpoint_dir: checkpoints_quick 