defaults:
  - bridge: skellam
  - model: energy_score
  - architecture: scformer
  - dataset: exprbyseq
  - training: expr
  - slack_sampler: bessel
  - _self_

model:
  m_samples: 8

# Hydra configuration
hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Global settings
device: cuda
seed: 42

# Experiment settings
experiment:
  name: "Sequence-to-Counts"
  version: "1.0"
  description: "Count-based flow matching with GPU bridges"

# Logging
logging:
  level: INFO

# Plotting (handled automatically by main.py)
create_plots: true 