_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

partition: normal
nodes: 1
gpus_per_node: 1
tasks_per_node: 1
cpus_per_task: 4
mem_gb: 32
timeout_min: 720
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
array_parallelism: 18

additional_parameters:
  gres: gpu:1
  exclude: dgx001,dgx002
  # include any node tagged ampere (A100) or any-A100, plus volta, turing, pascal
  constraint: "ampere|volta|turing|pascal"
  mail-type: END,FAIL
  mail-user: nfishman@g.harvard.edu

