# Constrained Skellam Bridge Configuration
_target_: bridges.cupy.constrained.SkellamMeanConstrainedBridge

# Bridge parameters
n_steps: ${n_steps}
schedule_type: "linear"
homogeneous_time: true
mh_sweeps: 1000

# M-sampler configuration
slack_sampler: ${slack_sampler}
delta: true