# Discrete Flow Bridge Configuration
_target_: bridges.baselines.dfm.DiscreteFlowBridge

# Bridge parameters
n_steps: ${n_steps}  # number of time steps for sampling
device: 0           # device for computations 