# Skellam Bridge Configuration
_target_: bridges.cupy.skellam.DiscreteFlowSkellamBridge

# Bridge parameters
n_steps: ${n_steps}
schedule_type: "linear"
homogeneous_time: false

# Slack sampler configuration
slack_sampler: ${slack_sampler}
delta: false