# Multimodal Bridge Configuration
_target_: bridges.torch.multimodal.MultiTimeDimensionalBridge

# Individual bridge configurations for each modality
bridges:
  img: 
    _target_: bridges.torch.diffusion.DiffusionBridge
    beta_min: 0.1
    beta_max: 20.0
    device: 0
  
  counts:
    _target_: bridges.cupy.skellam.SkellamBridge 
    schedule_type: "linear"
    slack_sampler: ${slack_sampler}