# Skellam Bridge Configuration
_target_: bridges.cupy.skellam.SkellamBridge

# Bridge parameters
schedule_type: "linear"
homogeneous_time: false

# Slack sampler configuration
slack_sampler: ${slack_sampler}
delta: false